pipeline {
  agent any
    
  tools {
    nodejs "NodeJS 18.14.2"
  }
  
  stages {
    stage('React Build') {
      steps {
        dir('frontend') {
          sh 'npm install'
          sh 'npm run build' 
        }
      }
    }
    
    stage('Docker Build') {
      steps {
        dir('frontend') {
          sh 'whoami'
          sh 'chmod -R 777 /var/jenkins_home/workspace/front'
          sh 'docker build -t edusepo-front:latest .'
        }
      }
    }
    
    stage('Deploy') {
      steps{
        sh 'docker rm -f front'
        sh 'docker run -d --name front -p 3126:3126 -u root edusepo-front:latest'
      }
    }

    stage('Finish') {
      steps{
        sh 'docker images -qf dangling=true | xargs -I{} docker rmi {}'
      }
    }
  }
}