pipeline {
  agent any
  
  stages {
    stage('Gradle Build') {
      steps {
        dir('backend/edusetpo') {
          sh 'chmod +x ./gradlew'
          sh './gradlew clean build -x test'
        }
      }
    }

    stage('Docker Build') {
      steps {
        dir('backend/edusetpo') {
          sh 'docker build -t edusepo-back:latest .'
        }
      }
    }
    
    stage('Deploy') {
      steps{
        sh 'docker rm -f back'
        sh 'docker run -d --name back -p 8080:8080 -u root -e TZ=Asia/Seoul edusepo-back:latest'
      }
    }

    stage('Finish') {
      steps{
        sh 'docker images -qf dangling=true | xargs -I{} docker rmi {}'
      }
    }
  }
}
