pipeline {
  agent any
  
  stages {
    stage('Gradle Build') {
      steps {
        dir('backend') {
          sh 'chmod +x ./edusetpo/gradlew'
            sh './edusetpo/gradlew clean build -x test'
        }
      }
    }

    stage('Docker Build') {
      steps {
        dir('backend') {
          sh 'docker build -t edusepo-back:latest .'
        }
      }
    }
    
    stage('Deploy') {
      steps{
        sh 'docker rm -f back'
        sh 'docker run -d --name back -p 8099:8099 -u root edusepo-back:latest'
      }
    }

    stage('Finish') {
      steps{
        sh 'docker images -qf dangling=true | xargs -I{} docker rmi {}'
      }
    }
  }
}